# Generated by Django 6.0.3 on 2026-08-12 06:32

from decimal import Decimal

from django.db import migrations, models


def seed_exchange_rates(apps, schema_editor):
    ExchangeRate = apps.get_model('wallet', 'ExchangeRate')
    ExchangeRate.objects.get_or_create(currency='USD', defaults={'rate_to_pkr': Decimal('278.50000000')})
    ExchangeRate.objects.get_or_create(currency='EUR', defaults={'rate_to_pkr': Decimal('301.00000000')})
    ExchangeRate.objects.get_or_create(currency='GBP', defaults={'rate_to_pkr': Decimal('350.00000000')})
    ExchangeRate.objects.get_or_create(currency='JPY', defaults={'rate_to_pkr': Decimal('1.85000000')})
    ExchangeRate.objects.get_or_create(currency='CHF', defaults={'rate_to_pkr': Decimal('312.00000000')})


def unseed_exchange_rates(apps, schema_editor):
    apps.get_model('wallet', 'ExchangeRate').objects.filter(currency__in=['USD', 'EUR', 'GBP', 'JPY', 'CHF']).delete()


class Migration(migrations.Migration):
    dependencies = [('wallet', '0003_transaction_description')]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('currency', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('rate_to_pkr', models.DecimalField(decimal_places=8, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(seed_exchange_rates, unseed_exchange_rates),
    ]
